version: '3'

services:
  app:
    image: "server"
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
  proxy:
    image: "nginx-server"
    container_name: nginx-server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "1000:1000"